resource_group_name = "engineer11"
resource_group_location = "West Europe"
virtual_network_name = "syllabus11"
subnet_name = "Unit11"
network_interface_name = "Theorem11"
virtual_machine_name = "Geotech11"
managed_disk_name = "M5011"
