resource_group_name = "HYDRA"
resource_group_location = "West Europe"
virtual_network_name = "SPECTRE"
subnet_name = "MI6"
public_ip_name = "MYIP"
network_interface_name = "SHIELD"
virtual_machine_name = "JARVIS"
managed_disk_name = "ARCH"
